title: goooooooooooogle
description: A starter template for a Jeykll site using the Just the Docs theme!
#theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

url: https://goooooooooooogle.github.io/just-the-docs-template

